version: '3.8'

services:
  # Redis 서비스
  redis:
    image: redis:alpine
    container_name: stockguard-redis
    ports:
      - "6379:6379"

  # FastAPI 서비스
  app:
    build: .
    container_name: fds-backend
    ports:
      - "8000:80"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
